version: '3.9'

services:
  postgresql:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/postgres/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/postgres/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgadmin4/pgpass
    depends_on:
      - postgresql

  #  http://localhost:1081/?pgsql=postgresql&username=postgres&db=postgres&ns=public
  adminer:
    image: adminer:4
    restart: always
    ports:
      - "1081:8080"

volumes:
  postgres-volume:
