version: '3.9'

services:
  scylla:
    image: scylladb/scylla:5.1.7
    command: --smp 1 --rpc-address 0.0.0.0 --broadcast-rpc-address localhost
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - "9042:9042"

volumes:
  scylla-data:
