version: '3.9'

services:

  keycloak_postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    restart: unless-stopped
    environment:
      KC_DB_VENDOR: POSTGRES
      KC_DB_ADDR: keycloak_postgres
      KC_DB_DATABASE: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: user
    volumes:
      - ./myrealm.json:/opt/keycloak/data/import/myrealm.json  # export_realm.bat
    ports:
      - "8080:8080"
    command:
      - start-dev --import-realm
    depends_on:
      - keycloak_postgres

volumes:
  keycloak-postgres-volume:
